insert into tbl_movie values('./영화포스터/공포/hr1.jpg', '29dayslater', '공포');
insert into tbl_movie values('./영화포스터/공포/hr2.jpg', 'getout', '공포');
insert into tbl_movie values('./영화포스터/공포/hr3.jpg', '나이트메어', '공포');
insert into tbl_movie values('./영화포스터/공포/hr4.jpg', '엑소시스트', '공포');
insert into tbl_movie values('./영화포스터/공포/hr5.jpg', '미드소마', '공포');
insert into tbl_movie values('./영화포스터/공포/hr6.jpg', '사일런트힐', '공포');
insert into tbl_movie values('./영화포스터/공포/hr7.jpg', '파라노말 액티비티', '공포');
insert into tbl_movie values('./영화포스터/공포/hr8.jpg', '할로윈', '공포');
insert into tbl_movie values('./영화포스터/공포/hr9.jpg', 'scarymovie', '공포');

insert into tbl_movie values('./영화포스터/SF/sf1.jpg', '스타트렉', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf2.jpg', '아바타 물의길', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf3.jpg', '블레이드', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf4.jpg', '인셉션', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf5.jpg', '스타워즈', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf6.jpg', 'quinto elemento', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf7.jpg', '인터스텔라', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf8.jpg', '엑스마키나', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf9.jpg', '마션', 'SF');
insert into tbl_movie values('./영화포스터/SF/sf10.jpg', '메트릭스', 'SF');

insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd1.jpg', '500일의 썸머', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd2.jpg', '나의 특별한 사랑이야기', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd3.jpg', '브리짓존스의 일기', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd4.jpg', '노팅힐', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd5.jpg', '시애틀의 잠못이루는 밤', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd6.jpg', '해리가 샐리를 만났을때', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd7.jpg', '프렌즈 워드 베네핏', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd8.jpg', 'October sky', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd9.jpg', 'Princess', '로맨스 코미디');
insert into tbl_movie values('./영화포스터/로맨스 코미디/lcd10.jpg', '러브 액츄얼리', '로맨스 코미디');

insert into tbl_movie values('./영화포스터/멜로/ml1.jpg', 'thenotebook', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml2.jpg', '브로크백마운틴', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml3.jpg', '블루발렌타인', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml4.jpg', '비포미드나잇', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml5.jpg', '사랑에 대한 모든 것', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml6.jpg', '셰익스피어 인 러브', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml7.jpg', 'about a boy', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml8.jpg', 'love actually notting hill', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml9.jpg', '이터널선샤인', '멜로');
insert into tbl_movie values('./영화포스터/멜로/ml10.jpg', 'prideprejudice', '멜로');

insert into tbl_movie values('./영화포스터/뮤지컬/msc1.jpg', 'the untouchables', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc2.jpg', '시카고', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc3.jpg', 'Les Miserables', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc4.jpg', '레이디스앤젠틀맨', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc5.jpg', '맘마미아!', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc6.jpg', '뮤지컬아이다', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc7.jpg', 'The phantom of the opera', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc8.jpg', 'cats', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc9.jpg', 'titanic', '뮤지컬');
insert into tbl_movie values('./영화포스터/뮤지컬/msc10.jpg', '포레스트 검프', '뮤지컬');

insert into tbl_movie values('./영화포스터/범죄/cr1.jpg', 'the godfather part 2', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr2.png', '펄프픽션', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr3.jpg', '대부', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr4.jpg', '무법자', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr5.jpg', 'The good the bad The ugly', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr6.jpg', '시티 오브 갓', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr7.jpg', 'Infernal Affairs', '범죄');
insert into tbl_movie values('./영화포스터/범죄/cr8.jpg', '좋은친구들', '범죄');

insert into tbl_movie values('./영화포스터/스릴러/sr1.jpg', 'saw', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr2.jpg', '셔터아일랜드', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr3.jpg', 'MISERY', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr4.jpg', '지.아이.조', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr5.jpg', '올드보이', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr6.jpg', 'BReaking Bad', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr7.jpg', '나이트크롤러', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr8.jpg', '싸이코', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr9.jpg', 'NIGHT OF THE LIVING DEAD', '스릴러');
insert into tbl_movie values('./영화포스터/스릴러/sr10.jpg', '쎄븐', '스릴러');

insert into tbl_movie values('./영화포스터/스포츠/sp1.jpg', '머니볼', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp2.jpg', 'RACING DREAMS', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp3.jpg', 'THE MIGHTY DUCKS', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp4.jpg', 'THE BLIND SIDE', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp5.jpg', '록키', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp6.jpg', 'TITANES', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp7.jpg', 'SEABISCUIT', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp8.jpg', 'RASTA ROCKETT', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp9.jpg', '크리드', '스포츠');
insert into tbl_movie values('./영화포스터/스포츠/sp10.jpg', 'POINT BREAK', '스포츠');

insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd1.jpg', '초능력자', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd2.jpg', '덤앤더머', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd3.jpg', '케이블가이', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd4.jpg', '나폴레옹 다이너마이트', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd5.jpg', 'SPACEBALLS', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd6.jpg', 'GREMLiNS', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd7.jpg', 'STEP BROTHERS', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd8.jpg', 'MACGRUBER', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd9.jpg', 'ANCHORMAN', '슬랩스틱 코미디');
insert into tbl_movie values('./영화포스터/슬랩스틱 코미디/scd10.jpg', 'HOT SHOTS', '슬랩스틱 코미디');

insert into tbl_movie values('./영화포스터/음악/ms1.jpg', '라라랜드', '음악');
insert into tbl_movie values('./영화포스터/음악/ms2.jpg', '오늘부터 댄싱퀸', '음악');
insert into tbl_movie values('./영화포스터/음악/ms3.jpg', 'mysticriver', '음악');
insert into tbl_movie values('./영화포스터/음악/ms4.jpg', 'bohemian', '음악');
insert into tbl_movie values('./영화포스터/음악/ms5.jpg', '비긴어게인', '음악');
insert into tbl_movie values('./영화포스터/음악/ms6.jpg', '아마데우스', '음악');
insert into tbl_movie values('./영화포스터/음악/ms7.jpg', '독수리에디', '음악');
insert into tbl_movie values('./영화포스터/음악/ms8.jpg', '원스', '음악');
insert into tbl_movie values('./영화포스터/음악/ms9.jpg', '위대한쇼맨', '음악');
insert into tbl_movie values('./영화포스터/음악/ms10.jpg', 'inside llewyn davis', '음악');

insert into tbl_movie values('./영화포스터/전쟁/war1.jpg', '덩케르크', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war2.jpg', '황산벌', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war3.jpg', '메건리비', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war4.jpg', 'saying private ryan', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war5.jpg', 'letters iwo jima', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war6.jpg', 'zero dark thirty', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war7.jpg', '태극기 휘날리며', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war8.jpg', 'Empire of the sun', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war9.jpg', '메탈자켓', '전쟁');
insert into tbl_movie values('./영화포스터/전쟁/war10.jpg', 'hunterKiller', '전쟁');

insert into tbl_movie values('./영화포스터/코미디/cd1.jpg', '행오버2', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd2.jpg', '나홀로집에', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd3.jpg', '신부의아버지', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd4.jpg', '코스트버스터즈', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd5.jpg', '트루먼쇼', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd6.jpg', '메리에겐 뭔가 특별한것이 있다', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd7.jpg', 'ace ventura', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd8.jpg', '10cosecheodiodite', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd9.jpg', '매디슨 카운터의 다리', '코미디');
insert into tbl_movie values('./영화포스터/코미디/cd10.jpg', '슈퍼배드2', '코미디');

insert into tbl_movie values('./영화포스터/판타지/ft1.jpg', '나니아연대기', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft2.jpg', '대혼돈의 멀티버스', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft3.jpg', 'miss peregrine', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft4.jpg', '반지의 제왕', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft5.jpg', '새짐', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft6.jpg', '스파이더맨', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft7.jpg', '신비한동물사전', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft8.jpg', '패왕별희', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft9.jpg', '퍼시잭슨과 올림포스의 신들', '판타지');
insert into tbl_movie values('./영화포스터/판타지/ft10.jpg', '해리포터', '판타지');
