INSERT INTO tbl_movie VALUES('hr1', './영화포스터/공포/hr1.jpg', '28일 후', '공포', '대니 보일', '킬리언 머피, 나오미 해리스');
INSERT INTO tbl_movie VALUES('hr2', './영화포스터/공포/hr2.jpg', '겟 아웃', '공포', '조던 필', '다니엘 칼루야, 앨리슨 윌리엄스');
INSERT INTO tbl_movie VALUES('hr3', './영화포스터/공포/hr3.jpg', '나이트메어', '공포', '웨스 크레이븐', '로버트 잉글런드, 헤더 랭겐캠프');
INSERT INTO tbl_movie VALUES('sf1', './영화포스터/SF/sf1.jpg', '스타트렉', 'SF', 'J.J. 에이브럼스', '크리스 파인, 재커리 퀸토');
INSERT INTO tbl_movie VALUES('sf2', './영화포스터/SF/sf2.jpg', '아바타 물의길', 'SF', '제임스 카메론', '샘 워싱턴, 조이 살다나');
INSERT INTO tbl_movie VALUES('sf3', './영화포스터/SF/sf3.jpg', '블레이드', 'SF', '스티븐 노린튼', '웨슬리 스나입스, 스티븐 도프');
INSERT INTO tbl_movie VALUES('ft3', './영화포스터/판타지/ft3.jpg', '미스 페레그린', '판타지', '팀 버튼', '에바 그린, 아사 버터필드');
INSERT INTO tbl_movie VALUES('lcd1', './영화포스터/로맨스 코미디/lcd1.jpg', '500일의 썸머', '로맨스 코미디', '마크 웹', '조셉 고든 레빗, 주이 디샤넬');
INSERT INTO tbl_movie VALUES('lcd2', './영화포스터/로맨스 코미디/lcd2.jpg', '나의 특별한 사랑이야기', '로맨스 코미디', '애덤 브룩스', '라이언 레이놀즈, 레이첼 와이즈');
INSERT INTO tbl_movie VALUES('lcd3', './영화포스터/로맨스 코미디/lcd3.jpg', '브리짓존스의 일기', '로맨스 코미디', '샤론 맥과이어', '르네 젤위거, 휴 그랜트');
INSERT INTO tbl_movie VALUES('ml1', './영화포스터/멜로/ml1.jpg', 'thenotebook', '멜로', '닉 카사베츠', '라이언 고슬링, 레이첼 맥아담스');
INSERT INTO tbl_movie VALUES('ml2', './영화포스터/멜로/ml2.jpg', '브로크백마운틴', '멜로', '이안', '히스 레저, 제이크 질렌할');
INSERT INTO tbl_movie VALUES('ml3', './영화포스터/멜로/ml3.jpg', '블루발렌타인', '멜로', '데렉 시언프랜스', '라이언 고슬링, 미셸 윌리엄스');
INSERT INTO tbl_movie VALUES('msc1', './영화포스터/뮤지컬/msc1.jpg', 'the untouchables', '뮤지컬', '정보 부족', '정보 부족');
INSERT INTO tbl_movie VALUES('msc2', './영화포스터/뮤지컬/msc2.jpg', '시카고', '뮤지컬', '롭 마샬', '르네 젤위거, 캐서린 제타 존스');
INSERT INTO tbl_movie VALUES('msc3', './영화포스터/뮤지컬/msc3.jpg', 'Les Miserables', '뮤지컬', '톰 후퍼', '휴 잭맨, 앤 해서웨이');
INSERT INTO tbl_movie VALUES('cr1', './영화포스터/범죄/cr1.jpg', 'the godfather part 2', '범죄', '프랜시스 포드 코폴라', '알 파치노, 로버트 드 니로');
INSERT INTO tbl_movie VALUES('cr2', './영화포스터/범죄/cr2.png', '펄프픽션', '범죄', '쿠엔틴 타란티노', '존 트라볼타, 우마 서먼');
INSERT INTO tbl_movie VALUES('cr3', './영화포스터/범죄/cr3.jpg', '대부', '범죄', '프랜시스 포드 코폴라', '말론 브란도, 알 파치노');
INSERT INTO tbl_movie VALUES('cr1', './영화포스터/스릴러/sr1.jpg', 'saw', '스릴러', '제임스 완', '리 워넬, 케리 엘위스');
INSERT INTO tbl_movie VALUES('cr2', './영화포스터/스릴러/sr2.jpg', '셔터아일랜드', '스릴러', '마틴 스코세이지', '레오나르도 디카프리오, 마크 러팔로');
INSERT INTO tbl_movie VALUES('cr3', './영화포스터/스릴러/sr3.jpg', 'MISERY', '스릴러', '롭 라이너', '제임스 칸, 캐시 베이츠');
INSERT INTO tbl_movie VALUES('sp1', './영화포스터/스포츠/sp1.jpg', '머니볼', '스포츠', '베넷 밀러', '브래드 피트, 조나 힐');
INSERT INTO tbl_movie VALUES('sp2', './영화포스터/스포츠/sp2.jpg', 'RACING DREAMS', '스포츠', '마셜 커리', '레이서 아이들 (다큐멘터리)');
INSERT INTO tbl_movie VALUES('sp3', './영화포스터/스포츠/sp3.jpg', 'THE MIGHTY DUCKS', '스포츠', '스티븐 헤렉', '에밀리오 에스테베즈, 조수아 잭슨');
INSERT INTO tbl_movie VALUES('scd1', './영화포스터/슬랩스틱 코미디/scd1.jpg', '초능력자', '슬랩스틱 코미디', '김민석', '강동원, 고수');
INSERT INTO tbl_movie VALUES('scd2', './영화포스터/슬랩스틱 코미디/scd2.jpg', '덤앤더머', '슬랩스틱 코미디', '피터 파렐리, 바비 파렐리', '짐 캐리, 제프 다니엘스');
INSERT INTO tbl_movie VALUES('scd3', './영화포스터/슬랩스틱 코미디/scd3.jpg', '케이블가이', '슬랩스틱 코미디', '벤 스틸러', '짐 캐리, 매튜 브로데릭');
INSERT INTO tbl_movie VALUES('ms1', './영화포스터/음악/ms1.jpg', '라라랜드', '음악', '데이미언 셔젤', '라이언 고슬링, 엠마 스톤');
INSERT INTO tbl_movie VALUES('ms2', './영화포스터/음악/ms2.jpg', '오늘부터 댄싱퀸', '음악', '오로카 고세', '리브 엘비라 쉬퍼순 라르손, 스툴라 하르비츠');
INSERT INTO tbl_movie VALUES('ms3', './영화포스터/음악/ms3.jpg', 'mysticriver', '음악', '클린트 이스트우드', '숀 펜, 팀 로빈스');
INSERT INTO tbl_movie VALUES('war1', './영화포스터/전쟁/war1.jpg', '덩케르크', '전쟁', '크리스토퍼 놀란', '킬리언 머피, 핀 화이트헤드');
INSERT INTO tbl_movie VALUES('war2', './영화포스터/전쟁/war2.jpg', '황산벌', '전쟁', '이준익', '박중훈, 정진영');
INSERT INTO tbl_movie VALUES('war3', './영화포스터/전쟁/war3.jpg', '메건리비', '전쟁', '가브리엘라 코퍼스웨이트', '케이트 마라');
INSERT INTO tbl_movie VALUES('cd1', './영화포스터/코미디/cd1.jpg', '행오버2', '코미디', '토드 필립스', '브래들리 쿠퍼, 에드 헬름스');
INSERT INTO tbl_movie VALUES('cd2', './영화포스터/코미디/cd2.jpg', '나홀로집에', '코미디', '크리스 콜럼버스', '맥컬리 컬킨, 조 페시');
INSERT INTO tbl_movie VALUES('cd3', './영화포스터/코미디/cd3.jpg', '신부의아버지', '코미디', '찰스 샤이어', '스티브 마틴, 다이앤 키튼');
INSERT INTO tbl_movie VALUES('ft1', './영화포스터/판타지/ft1.jpg', '나니아연대기', '판타지', '앤드류 아담슨', '조지 헨리, 스캔더 케인스');
INSERT INTO tbl_movie VALUES('ft2', './영화포스터/판타지/ft2.jpg', '대혼돈의 멀티버스', '판타지', '다니엘 콴, 다니엘 쉐이너트', '양자경, 키 호이 콴');